spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
    password:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  task:
    scheduling.pool.size: 10
